apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
  labels:
    account: webapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc1
  labels:
    account: svc1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc2
  labels:
    account: svc2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc3
  labels:
    account: svc3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc4
  labels:
    account: svc4
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc5
  labels:
    account: svc5
---