apiVersion: v1
kind: ConfigMap
metadata:
  name: dependencies-configmap
data:
  webapp-dependencies.yaml: |
    dependencies:
    - method: GET
      path: http://svc1.default.svc.cluster.local/
    - method: GET
      path: http://svc2.default.svc.cluster.local/

  svc1-dependencies.yaml: |
    dependencies:
    - method: GET
      path: http://svc3.default.svc.cluster.local/
   
  svc2-dependencies.yaml: |
    dependencies:
    - method: GET
      path: http://svc4.default.svc.cluster.local/
    - method: GET
      path: http://svc5.default.svc.cluster.local/

  svc3-dependencies.yaml: |
    dependencies:
    - method: GET
      path: http://svc4.default.svc.cluster.local/
    - method: GET
      path: http://svc5.default.svc.cluster.local/

  svc4-dependencies.yaml: |
    dependencies:

  svc5-dependencies.yaml: |
    dependencies:




